import { StyleSheet } from 'react-native';
import { GC } from '@/utils/glassColors';

// ============== 弹窗样式（Modal通用） ==============
export const m = StyleSheet.create({
  modalContainer: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.6)' },
  modalContent: { backgroundColor: GC.bgElevated, borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '85%', borderWidth: 1, borderColor: GC.border },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomWidth: 1, borderBottomColor: GC.border },
  modalTitle: { fontSize: 18, fontWeight: 'bold', color: GC.textPrimary },
  modalBody: { padding: 20 },
  modalFooter: { flexDirection: 'row', gap: 12, padding: 20, borderTopWidth: 1, borderTopColor: GC.border },
  modalBtn: { flex: 1, paddingVertical: 14, borderRadius: 12, alignItems: 'center' },
  cancelBtn: { backgroundColor: GC.border },
  cancelBtnText: { color: GC.textSecondary, fontSize: 16, fontWeight: '600' },
  submitBtn: { backgroundColor: GC.primary },
  submitBtnText: { color: GC.textPrimary, fontSize: 16, fontWeight: '600' },
  fieldLabel: { color: GC.textSecondary, fontSize: 13, fontWeight: '600', marginBottom: 6, marginTop: 12 },
  fieldInput: { backgroundColor: GC.inputBg, borderRadius: 10, padding: 14, color: GC.textPrimary, fontSize: 15, borderWidth: 1, borderColor: GC.border },
  promptInput: { minHeight: 120 },
  pickerWrap: { backgroundColor: GC.inputBg, borderRadius: 10, borderWidth: 1, borderColor: GC.border, maxHeight: 150 },
  pickerScroll: { padding: 8 },
  pickerItem: { paddingVertical: 10, paddingHorizontal: 14, borderRadius: 8 },
  pickerItemActive: { backgroundColor: GC.primary },
  pickerItemText: { color: GC.textSecondary, fontSize: 14 },
  pickerItemTextActive: { color: GC.textPrimary, fontWeight: '600' },
});

// ============== 页面样式 ==============
export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: GC.bgBase },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 60,
    paddingBottom: 16,
  },
  backBtn: { padding: 8 },
  headerTitle: { fontSize: 22, fontWeight: 'bold', color: GC.textPrimary },

  tabBar: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginBottom: 8,
    backgroundColor: GC.bgElevated,
    borderRadius: 12,
    padding: 4,
    borderWidth: 1,
    borderColor: GC.border,
  },
  tabItem: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 10 },
  tabItemActive: { backgroundColor: GC.primary },
  tabItemText: { color: GC.textSecondary, fontSize: 14, fontWeight: '600' },
  tabItemTextActive: { color: GC.textPrimary },

  scrollView: { flex: 1 },
  scrollContent: { padding: 20, paddingBottom: 100 },

  // 智能搭配
  smartMatchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: GC.bgElevated,
    borderRadius: 12,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#7C5CFF33',
    marginBottom: 20,
  },
  smartMatchBtnText: { color: GC.primary, fontSize: 15, fontWeight: '600' },

  // 全局铁律
  ironRulesWrap: { backgroundColor: GC.bgElevated, borderRadius: 12, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: 'rgba(229,160,13,0.25)' },
  ironRulesHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, gap: 6 },
  ironRulesTitle: { color: '#E5A00D', fontSize: 14, fontWeight: '700' },
  ironRulesHint: { color: GC.textMuted, fontSize: 11, marginLeft: 4 },
  ironRulesEditWrap: { gap: 8 },
  ironRulesInput: { backgroundColor: GC.bgBase, borderRadius: 10, padding: 12, color: GC.textPrimary, fontSize: 13, minHeight: 100, textAlignVertical: 'top', lineHeight: 20 },
  ironRulesBtnRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8 },
  ironRulesCancelBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, backgroundColor: GC.bgBase },
  ironRulesCancelText: { color: GC.textSecondary, fontSize: 13 },
  ironRulesSaveBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, backgroundColor: '#E5A00D' },
  ironRulesSaveText: { color: '#000', fontSize: 13, fontWeight: '600' },
  ironRulesDisplay: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  ironRulesContent: { flex: 1, color: GC.textSecondary, fontSize: 13, lineHeight: 20 },
  ironRulesEmpty: { flex: 1, color: GC.textMuted, fontSize: 13, fontStyle: 'italic' },

  // 分类标题
  categoryHeader: { marginTop: 16, marginBottom: 8, paddingLeft: 4 },
  categoryTitle: { color: GC.primary, fontSize: 13, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1.5 },

  // Agent卡片
  agentCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: GC.bgElevated,
    borderRadius: 14,
    padding: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: GC.border,
  },
  agentCardDisabled: { opacity: 0.5 },
  agentInfo: { flex: 1 },
  agentNameCol: { flex: 1, gap: 4 },
  agentName: { color: GC.textPrimary, fontSize: 16, fontWeight: '600' },
  agentDesc: { color: GC.textSecondary, fontSize: 13, marginTop: 2, lineHeight: 18 },
  agentApi: { color: GC.textMuted, fontSize: 12, marginTop: 4 },
  textDisabled: { color: GC.textMuted },
  agentRightActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },

  // 评审团
  sectionHeader: { marginTop: 16 },
  sectionTitle: { color: GC.textSecondary, fontSize: 13, fontWeight: '600', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 1 },
  sectionDesc: { color: GC.textMuted, fontSize: 12, marginBottom: 12 },

  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: GC.primary,
    borderRadius: 12,
    paddingVertical: 14,
    marginTop: 12,
  },
  addBtnText: { color: GC.textPrimary, fontSize: 15, fontWeight: '600' },

  resetBtn: { marginTop: 16, alignItems: 'center' },
  resetBtnText: { color: GC.textMuted, fontSize: 13 },

  iconBtn: { padding: 6 },

  // 评审参数
  divider: { height: 1, backgroundColor: GC.inputBg, marginTop: 24, marginBottom: 8 },
  fieldTitle: { color: GC.textSecondary, fontSize: 13, fontWeight: '600', marginBottom: 8, marginTop: 16 },
  reviewInput: {
    backgroundColor: GC.bgElevated,
    borderRadius: 10,
    padding: 14,
    color: GC.textPrimary,
    fontSize: 14,
    borderWidth: 1,
    borderColor: GC.border,
    minHeight: 60,
    textAlignVertical: 'top',
  },
  roundsRow: { flexDirection: 'row', gap: 10 },
  roundBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: GC.bgElevated,
    borderWidth: 1,
    borderColor: GC.border,
  },
  roundBtnActive: { backgroundColor: GC.primary, borderColor: GC.primary },
  roundBtnText: { color: GC.textSecondary, fontSize: 14, fontWeight: '600' },
  roundBtnTextActive: { color: GC.textPrimary },

  // API卡片
  apiCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: GC.bgElevated,
    borderRadius: 12,
    padding: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: GC.border,
  },
  apiInfo: { flex: 1 },
  apiName: { color: GC.textPrimary, fontSize: 16, fontWeight: '500' },
  apiDetail: { color: GC.textSecondary, fontSize: 12, marginTop: 2 },
  apiActions: { flexDirection: 'row', gap: 8 },

  // 测试规则按钮（卡片内）
  testBtn: {
    backgroundColor: GC.bgElevated,
    borderWidth: 1,
    borderColor: GC.accent,
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  testBtnText: { color: GC.accent, fontSize: 12, fontWeight: '600' },

  // 测试规则弹窗
  testOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
  testModal: { backgroundColor: GC.bgElevated, borderRadius: 20, width: '90%', maxHeight: '80%', borderWidth: 1, borderColor: GC.border, overflow: 'hidden' },
  testHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomWidth: 1, borderBottomColor: GC.border },
  testTitle: { fontSize: 18, fontWeight: 'bold', color: GC.textPrimary },
  testClose: { fontSize: 20, color: GC.textMuted },
  testBody: { padding: 20 },
  testStepBox: { marginBottom: 20 },
  testStepHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  testStepBadge: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  testStepBadgeText: { color: GC.textPrimary, fontSize: 13, fontWeight: '700' },
  testStepTitleText: { color: GC.textPrimary, fontSize: 16, fontWeight: '600', flex: 1 },
  testStepOk: { color: GC.success, fontSize: 13, fontWeight: '600' },
  testNoRule: { color: GC.textMuted, fontSize: 14, fontStyle: 'italic' },
  testLoadingText: { color: GC.textMuted, fontSize: 14, fontStyle: 'italic' },
  testRuleBox: {
    backgroundColor: GC.bgBase,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: GC.border,
    marginBottom: 16,
  },
  testRuleText: { color: GC.accent, fontSize: 15, lineHeight: 22 },
  testResultText: { color: GC.textPrimary, fontSize: 14, lineHeight: 22 },
  testResultTitle: { color: GC.textPrimary, fontSize: 15, fontWeight: '700', marginBottom: 8 },
  testResultPass: { color: GC.success, fontSize: 14, lineHeight: 22 },
  testResultBox: {
    backgroundColor: GC.bgBase,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: GC.border,
    minHeight: 80,
  },
  testFooter: { flexDirection: 'row', gap: 12, padding: 20, borderTopWidth: 1, borderTopColor: GC.border },
  testRunBtn: { flex: 1, backgroundColor: GC.primary, borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  testRunBtnText: { color: GC.textPrimary, fontSize: 16, fontWeight: '600' },
  testCancelBtn: { flex: 1, backgroundColor: GC.border, borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  testCancelBtnText: { color: GC.textSecondary, fontSize: 16, fontWeight: '600' },

  // 模板按钮行
  templateBtnRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 20,
  },
  importBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: GC.bgElevated,
    borderRadius: 12,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: GC.accent + '33',
  },
  importBtnText: { color: GC.accent, fontSize: 14, fontWeight: '600' },
  exportBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: GC.bgElevated,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: GC.border,
  },
  exportBtnText: { color: GC.textSecondary, fontSize: 14, fontWeight: '600' },

  // 预设模板列表
  presetTemplateList: { gap: 8 },
  presetTemplateBtn: {
    backgroundColor: GC.bgBase,
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: GC.border,
  },
  presetTemplateName: { color: GC.textPrimary, fontSize: 15, fontWeight: '600' },
  presetTemplateDesc: { color: GC.textMuted, fontSize: 12, marginTop: 2 },

  templateDivider: { height: 1, backgroundColor: GC.border, marginVertical: 16 },
  templateFormatHint: { color: GC.textMuted, fontSize: 11, marginBottom: 8, fontStyle: 'italic' },
  templateInput: { minHeight: 160, textAlignVertical: 'top' },

  importError: { color: '#FF6B6B', fontSize: 13, marginTop: 8 },

  // 导入预览
  importPreview: { marginTop: 12 },
  importPreviewTitle: { color: GC.accent, fontSize: 14, fontWeight: '600', marginBottom: 8 },
  importPreviewItem: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 4 },
  importPreviewStatus: { fontSize: 11, fontWeight: '700', color: GC.textPrimary, backgroundColor: GC.border, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, overflow: 'hidden' },
  importPreviewName: { color: GC.textPrimary, fontSize: 14, fontWeight: '500', width: 70 },
  importPreviewPrompt: { flex: 1, color: GC.textMuted, fontSize: 12 },
});
