import { StyleSheet } from 'react-native';
import { GC } from '@/utils/glassColors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: GC.bgBase },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 16,
  },
  headerTitle: { fontSize: 28, fontWeight: 'bold', color: GC.textPrimary },
  headerRight: { flexDirection: 'row', gap: 8 },
  multiModeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: GC.bgElevated,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
    borderWidth: 1,
    borderColor: GC.border,
  },
  multiModeBtnText: { color: GC.textPrimary, fontSize: 14, fontWeight: '500' },
  exitMultiBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: GC.bgElevated,
    borderWidth: 1,
    borderColor: '#ff6b6b33',
  },
  exitMultiBtnText: { color: GC.danger, fontSize: 14, fontWeight: '500' },
  scrollView: { flex: 1 },
  scrollContent: { padding: 20, paddingBottom: 100 },
  chapterBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: GC.bgElevated,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginBottom: 4,
    gap: 6,
    borderWidth: 1,
    borderColor: GC.border,
  },
  chapterText: { color: GC.textPrimary, fontSize: 15, fontWeight: '600' },
  switchingBar: {
    height: 3,
    backgroundColor: GC.bgElevated,
    borderRadius: 2,
    marginBottom: 16,
    overflow: 'hidden',
  },
  switchingProgress: {
    height: '100%',
    backgroundColor: GC.primary,
    borderRadius: 2,
    width: '60%',
  },
  outlineSection: { marginBottom: 16 },
  sectionLabel: { color: GC.textSecondary, fontSize: 13, marginBottom: 8, fontWeight: '500' },
  outlineDisplay: {
    backgroundColor: GC.bgElevated,
    borderRadius: 8,
    padding: 14,
    borderWidth: 1,
    borderColor: GC.border,
    maxHeight: 120,
  },
  outlineDisplayText: {
    color: GC.textSecondary,
    fontSize: 14,
    lineHeight: 22,
  },
  noOutlineHint: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: GC.bgElevated,
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: GC.border,
    gap: 8,
    marginBottom: 16,
  },
  noOutlineHintText: {
    color: GC.textMuted,
    fontSize: 13,
    flex: 1,
  },
  generateBtn: {
    backgroundColor: GC.primary,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    gap: 8,
    marginBottom: 16,
  },
  generateBtnDisabled: { opacity: 0.5 },
  generateBtnText: { color: '#fff', fontSize: 17, fontWeight: '600' },
  agentStatus: {
    backgroundColor: GC.bgElevated,
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: GC.border,
  },
  agentStatusTitle: { color: GC.textPrimary, fontSize: 14, fontWeight: '600', marginBottom: 10 },
  agentSteps: { gap: 8 },
  agentStepItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  stepDotPending: { width: 8, height: 8, borderRadius: 4, backgroundColor: GC.border },
  stepText: { fontSize: 12 },
  stepTextDone: { color: GC.success },
  stepTextCurrent: { color: GC.primary, fontWeight: '700' },
  stepTextPending: { color: GC.textSecondary },
  currentStepText: { color: GC.textPrimary, fontSize: 13, marginTop: 8 },
  contentSection: { marginTop: 8 },
  contentHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  previewBtn: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  previewBtnText: { color: GC.textSecondary, fontSize: 13 },
  contentCard: {
    backgroundColor: GC.bgElevated,
    borderRadius: 8,
    padding: 14,
    borderWidth: 1,
    borderColor: GC.border,
    minHeight: 200,
  },
  contentScroll: { maxHeight: 400 },
  contentText: { color: GC.textSecondary, fontSize: 15, lineHeight: 26 },
  actionButtons: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  rewriteBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: GC.primary,
    borderRadius: 10,
    paddingVertical: 12,
    gap: 6,
  },
  rewriteBtnText: { color: GC.textPrimary, fontSize: 15, fontWeight: '600' },
  saveBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: GC.primary,
    borderRadius: 10,
    paddingVertical: 12,
    gap: 6,
  },
  saveBtnText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  reviewBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: GC.border,
    borderRadius: 10,
    paddingVertical: 12,
    gap: 6,
    borderWidth: 1,
    borderColor: GC.textSecondary,
  },
  reviewBtnText: { color: GC.textPrimary, fontSize: 15, fontWeight: '600' },
  emptyContent: {
    alignItems: 'center',
    paddingVertical: 40,
    gap: 12,
  },
  emptyText: { color: GC.textMuted, fontSize: 14, textAlign: 'center' },

  // 多章模式
  multiHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  multiTitle: { color: GC.textPrimary, fontSize: 20, fontWeight: 'bold' },
  multiCount: { color: GC.textSecondary, fontSize: 14 },
  queueCard: {
    backgroundColor: GC.bgElevated,
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: GC.border,
  },
  queueCardActive: { borderColor: GC.primary, borderWidth: 2 },
  queueCardReviewed: { borderColor: '#4ade8044' },
  queueCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  queueCardTitle: { color: GC.textPrimary, fontSize: 16, fontWeight: '600' },
  queueCardActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  queueActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingVertical: 4,
  },
  statusRow: { marginTop: 6 },
  statusBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    backgroundColor: GC.border,
  },
  statusBadgeGenerating: { backgroundColor: '#fbbf2433' },
  statusBadgeDone: { backgroundColor: '#4ade8033' },
  statusBadgeReviewed: { backgroundColor: '#7C5CFF33' },
  statusBadgeText: { fontSize: 11, color: GC.textSecondary },
  queueOutlineText: {
    color: GC.textSecondary,
    fontSize: 12,
    marginTop: 8,
    lineHeight: 18,
  },
  queueNoOutlineText: {
    color: GC.danger,
    fontSize: 12,
    marginTop: 8,
    fontStyle: 'italic',
  },

  // 弹窗
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: GC.bgElevated,
    borderRadius: 16,
    padding: 24,
    width: '85%',
    borderWidth: 1,
    borderColor: GC.border,
  },
  reportModalContent: {
    backgroundColor: GC.bgElevated,
    borderRadius: 16,
    padding: 24,
    width: '90%',
    maxHeight: '80%',
    borderWidth: 1,
    borderColor: '#7C5CFF44',
  },
  modalTitle: { color: GC.textPrimary, fontSize: 20, fontWeight: 'bold', marginBottom: 8 },
  modalDesc: { color: GC.textSecondary, fontSize: 14, marginBottom: 20 },
  modalLabel: { color: GC.textSecondary, fontSize: 14, marginBottom: 8 },
  modalInfo: { color: GC.textSecondary, fontSize: 14, marginBottom: 12 },
  modalInput: {
    backgroundColor: GC.bgBase,
    borderRadius: 8,
    padding: 14,
    color: GC.textPrimary,
    fontSize: 16,
    borderWidth: 1,
    borderColor: GC.border,
    marginBottom: 12,
  },
  modalQuickRow: { flexDirection: 'row', gap: 10, marginBottom: 20 },
  modalQuickBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: GC.bgBase,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: GC.border,
  },
  modalQuickBtnActive: { borderColor: GC.primary, backgroundColor: '#7C5CFF22' },
  modalQuickBtnText: { color: GC.textSecondary, fontSize: 14 },
  modalQuickBtnTextActive: { color: GC.primary, fontWeight: '600' },
  modalButtons: { flexDirection: 'row', gap: 12, marginTop: 8 },
  modalCancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: GC.border,
    alignItems: 'center',
  },
  modalCancelText: { color: GC.textPrimary, fontSize: 15, fontWeight: '500' },
  modalConfirmBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: GC.primary,
    alignItems: 'center',
  },
  modalConfirmText: { color: GC.textPrimary, fontSize: 15, fontWeight: '600' },
  reportTitle: { color: GC.primary, fontSize: 18, fontWeight: 'bold', marginBottom: 12 },
  reportScroll: { maxHeight: 200, marginBottom: 12 },
  reportText: { color: GC.textSecondary, fontSize: 14, lineHeight: 22 },
  reportFeedbackLabel: { color: GC.textSecondary, fontSize: 12, marginBottom: 6 },
  reportFeedbackInput: {
    backgroundColor: GC.bgBase,
    borderRadius: 8,
    padding: 12,
    color: GC.textPrimary,
    fontSize: 14,
    borderWidth: 1,
    borderColor: GC.border,
    minHeight: 60,
    marginBottom: 12,
    textAlignVertical: 'top',
  },
  previewModalContainer: { flex: 1, backgroundColor: GC.bgBase },
  previewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: 60,
  },
  previewTitle: { color: GC.textPrimary, fontSize: 22, fontWeight: 'bold' },
  previewScroll: { flex: 1, padding: 20 },
  previewText: { color: GC.textSecondary, fontSize: 16, lineHeight: 28 },
});
